# Generated by Django 5.1.6 on 2025-03-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('NovelId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('ViewCount', models.IntegerField(default=0)),
                ('Description', models.TextField()),
                ('Author', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=50)),
                ('ChapCount', models.IntegerField(default=0)),
                ('ImgUrl', models.CharField(max_length=255)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('ChapId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Number', models.IntegerField()),
                ('Content', models.TextField()),
                ('Novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryNovel',
            fields=[
                ('CNId', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.category')),
                ('Novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentId', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.chapter')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserNovel',
            fields=[
                ('UNId', models.AutoField(primary_key=True, serialize=False)),
                ('Novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.user')),
            ],
        ),
    ]
