# Generated by Django 5.1.6 on 2025-03-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='ImgUrl',
            field=models.ImageField(upload_to='novel_images/'),
        ),
    ]
