# Generated by Django 3.1.12 on 2025-03-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='TotalComments',
            field=models.IntegerField(default=0),
        ),
    ]
