# Generated by Django 5.2 on 2025-05-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='categorynovel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usernovel',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='CategoryId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='categorynovel',
            name='CNId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='chapter',
            name='ChapId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='CommentId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='novel',
            name='NovelId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='usernovel',
            name='UNId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
