# Generated by Django 5.2 on 2025-05-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_remove_category_id_remove_categorynovel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='ImgFile',
            field=models.ImageField(blank=True, null=True, upload_to='novel_images/'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='ImgUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
