# Generated by Django 5.1.7 on 2025-03-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_alter_novel_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
