# Generated by Django 3.1.12 on 2025-04-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
