# Generated by Django 5.2 on 2025-05-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_novel_imgfile_alter_novel_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='ImgFile',
        ),
    ]
