# Generated by Django 5.2 on 2025-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_remove_novel_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='ImgUrl',
            field=models.ImageField(default=1, upload_to='novel_images/'),
            preserve_default=False,
        ),
    ]
