# Generated by Django 5.2 on 2025-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_alter_novel_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='ImgUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
