# Generated by Django 5.2 on 2025-05-19 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_alter_novel_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='Novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novel.novel'),
        ),
    ]
