# Generated by Django 5.2 on 2025-05-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_alter_chapter_novel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='Name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
