# Generated by Django 5.2 on 2025-05-22 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_alter_novel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_readers', to='novel.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='novel.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'novel')},
            },
        ),
    ]
