# Generated by Django 5.2 on 2025-05-24 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_readingprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='novel.novel'),
        ),
    ]
